/* ════════════════════════════════════════
   PROFILES (Mode Date) — FICHIER COMPLET
   ════════════════════════════════════════ */

const PROFILES = [

/* ════════════════════════════════════════
   LÉA — Aesthetic & vibes (INCHANGÉ)
══════════════════════════════════════════ */
{
  id: 'lea',
  gender: 'f',
  name: 'Léa',
  age: 23,
  emoji: '🌸',
  avatar: 'linear-gradient(135deg, #FF9A9E 0%, #FAD0C4 100%)',
  bio: 'Étudiante en psycho, aime les cafés cosy et les séries Netflix. Dit qu\'elle est "compliquée" dans sa bio Insta.',
  vibe: '✨ Aesthetic & vibes',
  flags: {
    'Instabilité émotionnelle': 'red',
    'Jalousie excessive':       'red',
    'A de l\'humour':           'green',
    'Attentionnée':             'green',
    'Addiction aux réseaux':    'red',
    'Besoin de proximité':      'neutral',
    'Amitiés durables':         'green',
    'Romantique':               'green',
    'Hygiène de vie saine':     'neutral',
    'Tient la barre (respect)': 'green',
  },
  warn3red:    "Ok là sérieusement… je vais être honnête, t'es pas vraiment ce que je cherche. Dernière chance hein 🙄",
  smash3green: "Attends… t'es vraiment trop bien toi 😍 Je pensais pas que ce date allait être aussi cool !",
  questions: [
    { type: 'choice', text: "Hé, j'avoue que je suis parfois un peu lunaire… ça te dérange si quelqu'un change d'humeur assez vite ?", topic: 'Instabilité émotionnelle',
      choices: [
        { label: "J'adore les gens intenses, ça me stimule", icon: '🔥', value: 'green' },
        { label: "Tant que c'est humain, ça va",             icon: '😌', value: 'neutral' },
        { label: "Franchement ça m'épuise vite",             icon: '😮‍💨', value: 'red' },
      ],
      reactions: { green: "Ah ouais tu comprends vraiment 😏 C'est rare.", neutral: "Ouais bof… réponse safe 😅", red: "Ouch. Bon, au moins t'es honnête je suppose… 😬" },
    },
    { type: 'flag', text: "« Je regarde encore parfois le téléphone de mon ex 😅 »", topic: 'Jalousie excessive', correct: 'red',
      reactions: { good: "Au moins toi t'es lucide, j'aime ça 😭", neutral: "Mouais… t'es pas très convaincu(e) là 😅", bad: "Aïe… tu trouves ça normal toi ? 😬" },
    },
    { type: 'choice', text: "L'humour dans un couple, t'en penses quoi ?", topic: 'A de l\'humour',
      choices: [
        { label: "C'est vital, sans ça j'tiens pas",  icon: '😂', value: 'green' },
        { label: "Ça aide, mais c'est pas tout",       icon: '😊', value: 'neutral' },
        { label: "Je suis plutôt du genre sérieux·se", icon: '🧐', value: 'red' },
      ],
      reactions: { green: "YES c'est tellement ça 🤣", neutral: "Hmm ouais… vision très pragmatique 😐", red: "Oh… on n'est clairement pas les mêmes 😶" },
    },
    { type: 'flag', text: "« Si quelqu'un répond pas pendant 1h je peux vriller 😭 »", topic: 'Besoin de proximité', correct: 'red',
      reactions: { good: "Ouais je sais, c'est pas ouf de ma part 😭 Mais bon.", neutral: "T'as pas vraiment d'avis là-dessus ? 🤔", bad: "Tu trouves ça normal de vriller après 1h ?! 😂" },
    },
    { type: 'choice', text: "Les petites attentions romantiques — fleurs, messages le matin — t'aimes ça ?", topic: 'Romantique',
      choices: [
        { label: "J'adore, c'est trop mignon",  icon: '💐', value: 'green' },
        { label: "De temps en temps ouais",      icon: '😊', value: 'neutral' },
        { label: "Je trouve ça un peu cliché",   icon: '🙄', value: 'red' },
      ],
      reactions: { green: "On est trop pareils là 🥺 J'y crois pas.", neutral: "Ok… version économie de sentiments 😅", red: "Ah. Ça dit beaucoup sur toi ça 😕" },
    },
    { type: 'flag', text: "« Je préfère toujours parler calmement plutôt que crier »", topic: 'Attentionnée', correct: 'green',
      reactions: { good: "Ça c'est mature, j'aime vraiment 😌", neutral: "Bof, t'es pas convaincu(e) ? 🤨", bad: "Tu préfères les cris ? Ok… 😭" },
    },
    { type: 'choice', text: "T'es du genre à être accro à ton téléphone ou tu sais déconnecter ?", topic: 'Addiction aux réseaux',
      choices: [
        { label: "Je déconnecte facilement",        icon: '🧘', value: 'green' },
        { label: "Ça dépend des moments",            icon: '📵', value: 'neutral' },
        { label: "Mon téléphone est ma vie lol",     icon: '📱', value: 'red' },
      ],
      reactions: { green: "Ah enfin quelqu'un de sain 😂", neutral: "Réponse très diplomatique 😏", red: "Ah ouais on est pareils alors 😅" },
    },
    { type: 'flag', text: "« J'ai mes meilleures amies depuis le collège, on se voit encore tous les mois »", topic: 'Amitiés durables', correct: 'green',
      reactions: { good: "Les relations stables c'est tellement important 😌", neutral: "Mouais, t'es mitigé(e) ? 🤔", bad: "Tu trouves ça bizarre d'avoir des amis fidèles ? 😳" },
    },
  ],
  endings: {
    smash: { emoji: '😍', text: "Ok c'est officiel, t'es exactement ce que je cherchais. On se revoit quand ?" },
    high:  { emoji: '🥰', text: "J'avoue, t'es vraiment cool. Ce date était une bonne surprise." },
    mid:   { emoji: '🤔', text: "C'est compliqué… t'as des qualités mais on est pas forcément sur la même longueur d'onde." },
    low:   { emoji: '😬', text: "Hmm… je pense qu'on est pas très compatibles toi et moi." },
    pass:  { emoji: '🚩', text: "Non. Vraiment non. Je pense qu'on est pas faits pour être ensemble." },
  },
},

/* ════════════════════════════════════════
   ELEA — Chaos nocturne & gaming (INCHANGÉ)
══════════════════════════════════════════ */
{
  id: 'elea',
  gender: 'f',
  name: 'Elea',
  age: 18,
  emoji: '🌙',
  avatar: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
  bio: 'Je change de mec toutes les deux semaines et je kiff ça. Ma passion : Elden Ring et la Red Bull !!!',
  vibe: '🌃 Modératrice Discord, vit la nuit.',
  flags: {
    'Vie nocturne':             'red',
    'Parle à 20 mecs':          'red',
    'Sportive (rugby)':         'green',
    'Instabilité émotionnelle': 'red',
    'Addiction PC/Téléphone':   'red',
    'Crie souvent':             'red',
    'Humour gamer':             'green',
    'Franchise':                'green',
    'Besoin d\'attention':      'neutral',
    'Énergie extrême':          'neutral',
  },
  warn3red:    "Franchement… t'as l'air d'avoir peur des filles un peu intenses 😒",
  smash3green: "Attends quoi ?? T'es vraiment en train de matcher mon énergie là 😳🔥",
  questions: [
    { type: 'choice', text: "Je dors souvent à 6h du mat et je vis surtout la nuit… ça te dérange ?", topic: 'Vie nocturne',
      choices: [
        { label: "Non, j'adore les vibes nocturnes", icon: '🌙', value: 'green' },
        { label: "Tant que t'es en forme ça va",     icon: '😌', value: 'neutral' },
        { label: "Impossible pour moi ce rythme",    icon: '☀️', value: 'red' },
      ],
      reactions: { green: "YES enfin quelqu'un qui comprend 😭", neutral: "Mouais… réponse un peu fade 😅", red: "Ouch ok monsieur/madame 21h dodo 😭" },
    },
    { type: 'flag', text: "« Je parle à plusieurs mecs en même temps »", topic: 'Parle à 20 mecs', correct: 'red',
      reactions: { good: "Au moins toi t'as compris que c'est toxique 😭", neutral: "T'es mitigé là 🤨", bad: "Ah ouais toi aussi t'es un danger 😭" },
    },
    { type: 'choice', text: "Tu trouves ça attirant une fille qui joue au rugby ?", topic: 'Sportive (rugby)',
      choices: [
        { label: "Carrément, c'est stylé",    icon: '🏉', value: 'green' },
        { label: "Pourquoi pas honnêtement",  icon: '😌', value: 'neutral' },
        { label: "Pas du tout mon délire",    icon: '🙄', value: 'red' },
      ],
      reactions: { green: "Enfin quelqu'un qui respecte les vraies sportives 😌", neutral: "Bon… au moins t'es ouvert 😅", red: "Ah ouais carrément 😭" },
    },
    { type: 'choice', text: "Je peux passer d'hyper heureuse à énervée très vite 😭 Tu gères ça comment ?", topic: 'Instabilité émotionnelle',
      choices: [
        { label: "Je suis patient(e)",           icon: '🫶', value: 'green' },
        { label: "Ça dépend des situations",     icon: '🤔', value: 'neutral' },
        { label: "Je déteste les dramas",        icon: '😮‍💨', value: 'red' },
      ],
      reactions: { green: "Ok toi t'as de la patience 😂", neutral: "Réponse très diplomatique 😭", red: "Bon bah au moins c'est clair 😬" },
    },
    { type: 'flag', text: "« Je passe littéralement toute ma vie sur mon PC et mon téléphone »", topic: 'Addiction PC/Téléphone', correct: 'red',
      reactions: { good: "Oui bon… faut toucher de l'herbe parfois 😭", neutral: "Mouais t'as pas d'avis quoi 😅", bad: "Ah ouais toi aussi t'es matrixé 😭" },
    },
    { type: 'choice', text: "Quand je suis énervée, je peux facilement crier 😅", topic: 'Crie souvent',
      choices: [
        { label: "Je préfère les gens calmes", icon: '😌', value: 'green' },
        { label: "Ça arrive à tout le monde",  icon: '🤷', value: 'neutral' },
        { label: "J'adore les disputes",       icon: '🔥', value: 'red' },
      ],
      reactions: { green: "Ok t'as l'air mature toi 😭", neutral: "Bon… acceptable 😅", red: "PTDR relation explosive alors 😭" },
    },
    { type: 'choice', text: "Une soirée parfaite pour toi ?", topic: 'Humour gamer',
      choices: [
        { label: "Gaming + bouffe + Discord", icon: '🎮', value: 'green' },
        { label: "Un peu de tout",            icon: '🍕', value: 'neutral' },
        { label: "Sortir loin des écrans",    icon: '🌳', value: 'red' },
      ],
      reactions: { green: "OK incroyable la vibe 😭", neutral: "Ça passe encore 😌", red: "Aïe… incompatible gamer 😭" },
    },
    { type: 'flag', text: "« Je dis toujours ce que je pense même si ça pique »", topic: 'Franchise', correct: 'green',
      reactions: { good: "Merciii enfin quelqu'un qui aime l'honnêteté 😭", neutral: "T'es pas convaincu 😅", bad: "Tu préfères les faux gens ? 😭" },
    },
    { type: 'choice', text: "Question très importante : Red Bull ou Monster ? 👀", topic: 'Énergie extrême',
      choices: [
        { label: "Red Bull évidemment",  icon: '🔵', value: 'green' },
        { label: "Monster sans hésiter", icon: '🟢', value: 'neutral' },
        { label: "Aucune des deux 😭",   icon: '💧', value: 'red' },
      ],
      reactions: { green: "YESSS quelqu'un de cultivé enfin 😭", neutral: "Bon… acceptable j'imagine 😅", red: "Comment tu survis sans caféine toi 😭" },
    },
    { type: 'flag', text: "« J'ai un bodycount de 8 😭 »", topic: 'Franchise', correct: 'neutral',
      reactions: { good: "Au moins t'es mature là-dessus 😌", neutral: "Réponse très safe 😭", bad: "Oulaaa ça juge fort ici 😬" },
    },
  ],
  endings: {
    smash: { emoji: '😍', text: "Ok toi et moi c'est le chaos parfait. On refait une nuit blanche ensemble quand ?" },
    high:  { emoji: '🥰', text: "Franchement t'es cool… j'pensais pas autant matcher avec quelqu'un 😌" },
    mid:   { emoji: '🤔', text: "On a quelques points communs… mais aussi pas mal de différences 😅" },
    low:   { emoji: '😬', text: "Hmm… je pense qu'on vivrait pas du tout au même rythme 😭" },
    pass:  { emoji: '🚩', text: "Non vraiment… toi et moi ça finirait en guerre mondiale 💀" },
  },
},

/* ════════════════════════════════════════
   MANON — Sportive, mental acier
══════════════════════════════════════════ */
{
  id: 'manon',
  gender: 'f',
  name: 'Manon',
  age: 21,
  emoji: '🏅',
  avatar: 'linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)',
  bio: 'Athlète semi-pro, lève à 6h même le dimanche. Je supporte pas les excuses et les gens qui renoncent.',
  vibe: '💪 Sport & performance',
  flags: {
    'Sport quotidien':     'green',
    'Mental de winner':    'green',
    'Discipline de fer':   'green',
    'Peu de patience':     'red',
    'Excuses = dealbreak': 'red',
    'Compétitive':         'neutral',
    'Directe':             'green',
    'Peu de vie sociale':  'neutral',
  },
  warn3red:    "T'as l'air d'être du genre à trouver des excuses… c'est vraiment pas mon truc 😤",
  smash3green: "Ok là respect total. Enfin quelqu'un qui comprend ce que c'est d'aller au bout 🔥",
  questions: [
    { type: 'choice', text: "Je m'entraîne minimum 1h30 par jour, même fatigué·e. T'es comment toi avec le sport ?", topic: 'Sport quotidien',
      choices: [
        { label: "Je m'entraîne régulièrement aussi",    icon: '🏋️', value: 'green' },
        { label: "Je fais du sport quand j'en ai envie", icon: '😌', value: 'neutral' },
        { label: "Franchement j'y vais pas souvent",     icon: '🛋️', value: 'red' },
      ],
      reactions: { green: "Ok respect, on est sur la même longueur d'onde 💪", neutral: "« Quand t'en as envie »… ça se travaille ça 😐", red: "Je vais être honnête… c'est compliqué pour moi ça 😬" },
    },
    { type: 'flag', text: "« Je lâche jamais, même quand c'est dur »", topic: 'Mental de winner', correct: 'green',
      reactions: { good: "C'est exactement ça 🔥 Les gens qui lâchent pas c'est rare.", neutral: "Hmm… pas très convaincu(e) ? 🤔", bad: "Tu trouves que lâcher c'est ok ? On a un problème là 😭" },
    },
    { type: 'choice', text: "T'as un objectif important. T'as pas envie d'y aller. Tu fais quoi ?", topic: 'Discipline de fer',
      choices: [
        { label: "J'y vais quand même, c'est pas discutable", icon: '🎯', value: 'green' },
        { label: "Je me force mais c'est dur",                icon: '😅', value: 'neutral' },
        { label: "Je remets à demain honnêtement",            icon: '😴', value: 'red' },
      ],
      reactions: { green: "Voilà. C'est ça la vraie discipline 😌", neutral: "Au moins t'es honnête… mais c'est le minimum 🫤", red: "Demain. Toujours demain. Et demain ça arrive jamais 😑" },
    },
    { type: 'flag', text: "« J'ai raté ma séance parce que j'avais pas le temps »", topic: 'Excuses = dealbreak', correct: 'red',
      reactions: { good: "Exactement. « Pas le temps » c'est une excuse, point.", neutral: "T'es tolérant(e) là-dessus toi… 🤔", bad: "T'excuses ça vraiment ? On a des valeurs différentes 😅" },
    },
    { type: 'choice', text: "La compétition, ça te motive ou ça te stresse ?", topic: 'Compétitive',
      choices: [
        { label: "Je kiff gagner, ça me booste",            icon: '🏆', value: 'green' },
        { label: "J'aime me dépasser mais sans pression",   icon: '😌', value: 'neutral' },
        { label: "Je préfère faire les choses sans enjeu",  icon: '😅', value: 'red' },
      ],
      reactions: { green: "Ouais c'est ça ! La gagne c'est un état d'esprit 🔥", neutral: "C'est honorable. Un peu sage à mon goût 😏", red: "Pas d'enjeu… pas de progression non plus selon moi 🫤" },
    },
    { type: 'flag', text: "« Je suis directe, je dis les choses sans tourner autour »", topic: 'Directe', correct: 'green',
      reactions: { good: "Pareil. Les non-dits c'est la source de tous les problèmes 😌", neutral: "T'es mitigé(e)… tu préfères les sous-entendus ? 🤔", bad: "Tu préfères quand on tourne autour du pot ? 😑" },
    },
    { type: 'choice', text: "Quelqu'un annule un plan au dernier moment sans vraie raison. Tu réagis comment ?", topic: 'Peu de patience',
      choices: [
        { label: "Je lui dis clairement que c'est irrespectueux", icon: '😤', value: 'green' },
        { label: "Je suis déçu(e) mais je laisse passer",         icon: '😔', value: 'neutral' },
        { label: "Ça arrive, j'en fais pas un drame",             icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Exactement. Le respect du temps des autres c'est basique 😌", neutral: "Laisser passer… c'est les encourager à recommencer 😐", red: "T'as de la patience toi… peut-être trop 😅" },
    },
    { type: 'flag', text: "« J'ai sacrifié des soirées pour progresser »", topic: 'Peu de vie sociale', correct: 'green',
      reactions: { good: "T'es le/la rare qui comprend ce que ça coûte vraiment 🔥", neutral: "Mouais, pas totalement convaincu(e) 🤔", bad: "Aucun sacrifice ? Alors aucun vrai objectif 😒" },
    },
    { type: 'choice', text: "Dernier truc : alimentation. T'es plutôt comment ?", topic: 'Discipline de fer',
      choices: [
        { label: "Je fais attention à ce que je mange",     icon: '🥗', value: 'green' },
        { label: "J'essaie mais j'suis pas parfait(e)",     icon: '🍕', value: 'neutral' },
        { label: "Je mange n'importe quoi franchement",     icon: '🍔', value: 'red' },
      ],
      reactions: { green: "Cuisine propre, tête claire. On se ressemble 💪", neutral: "Ok… au moins t'es honnête 😅", red: "Le sport sans la nutrition ça sert à rien… mais ok 😑" },
    },
  ],
  endings: {
    smash: { emoji: '🏆', text: "Ok. T'es le/la seul(e) que j'ai rencontré qui comprend vraiment. On se revoit." },
    high:  { emoji: '🥰', text: "Franchement… t'es solide. Ce date était une bonne surprise." },
    mid:   { emoji: '🤔', text: "T'as des qualités mais on est pas sur le même niveau d'exigence." },
    low:   { emoji: '😬', text: "Je pense qu'on a une vision trop différente de l'effort." },
    pass:  { emoji: '🚩', text: "Non. T'es trop cool avec la médiocrité pour moi." },
  },
},

/* ════════════════════════════════════════
   NORA — Gothique, sarcasme & profondeur
══════════════════════════════════════════ */
{
  id: 'nora',
  gender: 'f',
  name: 'Nora',
  age: 20,
  emoji: '🖤',
  avatar: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
  bio: 'Cimetières, Baudelaire, metal symphonique. Je fuis les gens trop positifs.',
  vibe: '🖤 Dark & poétique',
  flags: {
    'Esthétique dark':        'green',
    'Sarcasme permanent':     'green',
    'Peu sociable':           'neutral',
    'Très introspective':     'green',
    'Déprime saisonnière':    'red',
    'Créative':               'green',
    'Solitude revendiquée':   'neutral',
    'Sensible sous la carapace': 'green',
  },
  warn3red:    "Trop de lumière dans ton âme… je pense qu'on vit dans des univers parallèles 🕯️",
  smash3green: "Ok. T'es la première personne qui me comprend sans essayer de me « sauver ». C'est rare 🖤",
  questions: [
    { type: 'choice', text: "Je porte du noir 365 jours par an. T'as un problème avec ça ?", topic: 'Esthétique dark',
      choices: [
        { label: "Non, c'est même très stylé",         icon: '🖤', value: 'green' },
        { label: "Tant que t'es à l'aise",             icon: '😌', value: 'neutral' },
        { label: "Tu devrais essayer les couleurs",    icon: '🌈', value: 'red' },
      ],
      reactions: { green: "Enfin quelqu'un qui comprend l'esthétique 🖤", neutral: "Réponse polie. Trop polie.", red: "Les couleurs. Classique. 🙄" },
    },
    { type: 'flag', text: "« Je préfère les musées la nuit, les parcs déserts et les librairies vides »", topic: 'Peu sociable', correct: 'green',
      reactions: { good: "T'as compris la vraie beauté des endroits sans gens 🖤", neutral: "Mouais… t'as pas l'air très convaincu(e) 😑", bad: "Trop solitaire pour toi ? Tu manques quelque chose alors." },
    },
    { type: 'choice', text: "Le sarcasme en permanence, ça te convient ou ça t'épuise ?", topic: 'Sarcasme permanent',
      choices: [
        { label: "J'adore, c'est une forme d'intelligence",  icon: '😏', value: 'green' },
        { label: "Ça dépend du contexte",                    icon: '🤔', value: 'neutral' },
        { label: "Je préfère la sincérité directe",          icon: '😐', value: 'red' },
      ],
      reactions: { green: "T'as compris 😏 Le sarcasme c'est de la tendresse déguisée.", neutral: "« Ça dépend »… réponse de quelqu'un qui veut plaire à tout le monde.", red: "La sincérité directe… tu vas souffrir avec moi alors 😌" },
    },
    { type: 'flag', text: "« Je lis Baudelaire pour me sentir moins seule »", topic: 'Très introspective', correct: 'green',
      reactions: { good: "« Les fleurs du mal » comme thérapie. T'es cultivé(e) 🖤", neutral: "T'as l'air mitigé(e) là-dessus 🤔", bad: "Baudelaire c'est déprimant pour toi ? Ah. Ok." },
    },
    { type: 'choice', text: "Une soirée parfaite pour toi ?", topic: 'Solitude revendiquée',
      choices: [
        { label: "Bougies, vinyle, livre ou dessin",   icon: '🕯️', value: 'green' },
        { label: "Film sombre avec quelqu'un",         icon: '🎬', value: 'neutral' },
        { label: "Sortir avec des gens",               icon: '🎉', value: 'red' },
      ],
      reactions: { green: "On vit pareil 🖤", neutral: "Ok je peux faire une exception pour quelqu'un bien 😌", red: "Sortir. Avec des gens. Volontairement. 😑" },
    },
    { type: 'flag', text: "« J'ai pleuré devant un tableau dans un musée »", topic: 'Sensible sous la carapace', correct: 'green',
      reactions: { good: "La sensibilité cachée c'est la plus vraie 🖤", neutral: "T'es sceptique ? Les émotions devant l'art c'est humain.", bad: "Pleurer devant de l'art ? Tu penses que c'est bizarre ? Je te plains." },
    },
    { type: 'choice', text: "Les gens trop positifs, trop « bonne énergie »… ça te fait quoi ?", topic: 'Peu sociable',
      choices: [
        { label: "Ça me fatigue profondément",          icon: '😶‍🌫️', value: 'green' },
        { label: "C'est bien pour eux, tant mieux",    icon: '😌', value: 'neutral' },
        { label: "J'aime bien les gens joyeux",         icon: '☀️', value: 'red' },
      ],
      reactions: { green: "L'optimisme forcé c'est le pire mensonge social 😌", neutral: "Très tolérant(e) toi… 🤔", red: "T'es solaire toi. On est pas compatibles." },
    },
    { type: 'flag', text: "« Je suis pas dépressive, je suis juste lucide »", topic: 'Déprime saisonnière', correct: 'neutral',
      reactions: { good: "Exactement la nuance 🖤", neutral: "Réponse de quelqu'un qui réfléchit, j'apprécie.", bad: "T'aurais pas dû marquer ça comme négatif 🙄" },
    },
    { type: 'choice', text: "Metal symphonique, dark folk, post-rock… t'aimes ça ?", topic: 'Esthétique dark',
      choices: [
        { label: "Oui, totalement mon univers",    icon: '🎸', value: 'green' },
        { label: "Je connais un peu, pas fermé(e)", icon: '🤔', value: 'neutral' },
        { label: "Je comprends pas ce genre",      icon: '🎵', value: 'red' },
      ],
      reactions: { green: "On peut écouter Heilung ensemble alors 🖤", neutral: "Bien. L'ouverture musicale c'est pas donné à tout le monde.", red: "C'est là qu'on voit les limites 😑" },
    },
  ],
  endings: {
    smash: { emoji: '🖤', text: "T'es le/la seul(e) qui m'a pas demandé de sourire davantage. On se revoit." },
    high:  { emoji: '🥀', text: "T'es pas si insupportable que les autres. C'est un compliment." },
    mid:   { emoji: '🤔', text: "T'es correct(e). Mais on a des visions trop différentes du monde." },
    low:   { emoji: '😬', text: "T'es trop lumineux·se pour moi je crois." },
    pass:  { emoji: '🚩', text: "Non. T'es exactement le genre de personnes que j'évite." },
  },
},

/* ════════════════════════════════════════
   SAMIRA — Sporty & fière de ses origines
══════════════════════════════════════════ */
{
  id: 'samira',
  gender: 'f',
  name: 'Samira',
  age: 22,
  emoji: '🌙',
  avatar: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
  bio: 'Kiné en formation, famille avant tout. Je sors pas avec n\'importe qui.',
  vibe: '✨ Ambitieuse & ancrée',
  flags: {
    'Famille = priorité':     'green',
    'Ambitieuse':             'green',
    'Valeurs fortes':         'green',
    'Intransigeante':         'neutral',
    'Riche culturellement':   'green',
    'Impatiente parfois':     'red',
    'Franche':                'green',
    'Sélective en amour':     'neutral',
  },
  warn3red:    "Je vais être directe : t'as pas l'air sérieux·se. Et le temps c'est précieux 🙄",
  smash3green: "Waw… t'es vraiment différent(e) de ce que je rencontre habituellement. Vraiment 😮",
  questions: [
    { type: 'choice', text: "La famille dans ma vie c'est tout. T'es comment avec la tienne ?", topic: 'Famille = priorité',
      choices: [
        { label: "Super proche aussi, c'est fondamental",  icon: '👨‍👩‍👧', value: 'green' },
        { label: "Bonne relation mais distance nécessaire", icon: '😌', value: 'neutral' },
        { label: "On est pas très proches honnêtement",    icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Les gens ancrés dans leur famille c'est rare et précieux 😌", neutral: "Ok… ça s'entend.", red: "Ça se travaille parfois. J'espère que c'est pas un choix." },
    },
    { type: 'flag', text: "« Je fais la différence entre sortir et construire quelque chose »", topic: 'Sélective en amour', correct: 'green',
      reactions: { good: "Exactement. Les gens sérieux c'est de plus en plus rares 😌", neutral: "T'es mitigé(e) là 🤔", bad: "Tu fais pas la différence ? C'est un problème." },
    },
    { type: 'choice', text: "Je suis en études longues, j'ai pas forcément beaucoup de temps libre. Ça te convient ?", topic: 'Ambitieuse',
      choices: [
        { label: "Aucun problème, j'admire l'ambition",        icon: '📚', value: 'green' },
        { label: "Tant qu'on s'organise, ça peut aller",       icon: '📅', value: 'neutral' },
        { label: "J'ai besoin de beaucoup de disponibilité",   icon: '😕', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui comprend que les études c'est un investissement 😌", neutral: "L'organisation ça se fait, ok.", red: "Ah. T'as besoin de beaucoup de présence… c'est compliqué pour moi." },
    },
    { type: 'flag', text: "« Je parle arabe à la maison, français dehors, et je jongle entre les deux cultures »", topic: 'Riche culturellement', correct: 'green',
      reactions: { good: "Le bilinguisme culturel c'est une vraie richesse 😌", neutral: "Réponse safe 😅", bad: "Ça t'a pas l'air de t'impressionner… c'est dommage." },
    },
    { type: 'choice', text: "Quelqu'un qui fait des blagues sur les origines ou la religion, tu réagis comment ?", topic: 'Valeurs fortes',
      choices: [
        { label: "Je recadre immédiatement, c'est pas négociable", icon: '✋', value: 'green' },
        { label: "Ça dépend du contexte et de l'humour",          icon: '🤔', value: 'neutral' },
        { label: "J'essaie pas de créer de conflit",              icon: '😅', value: 'red' },
      ],
      reactions: { green: "Bien. Les limites c'est pas de la sensibilité, c'est du respect.", neutral: "Le « contexte »… ça peut servir d'excuse à tout.", red: "Éviter le conflit c'est laisser passer des choses qu'on devrait pas laisser passer." },
    },
    { type: 'flag', text: "« Je suis ambitieuse, je veux réussir professionnellement »", topic: 'Ambitieuse', correct: 'green',
      reactions: { good: "L'ambition féminine c'est attractive, clairement 😌", neutral: "Pas très convaincu(e) ? 🤔", bad: "Tu préfères les gens sans ambition ? Bizarre." },
    },
    { type: 'choice', text: "Qu'est-ce qui t'attire chez quelqu'un en premier ?", topic: 'Sélective en amour',
      choices: [
        { label: "Le sérieux et les valeurs",         icon: '🤝', value: 'green' },
        { label: "L'humour et la spontanéité",        icon: '😄', value: 'neutral' },
        { label: "L'apparence avant tout",            icon: '👀', value: 'red' },
      ],
      reactions: { green: "Quelqu'un de mature 😌 C'est exactement ça.", neutral: "L'humour c'est bien mais ça construit pas grand chose seul.", red: "Ah. L'apparence. Classique." },
    },
    { type: 'choice', text: "T'as combien de vraies amies proches ?", topic: 'Franche',
      choices: [
        { label: "Peu mais de vraies, solides",      icon: '🤝', value: 'green' },
        { label: "Un cercle moyen, assez large",     icon: '👥', value: 'neutral' },
        { label: "Plein de connaissances partout",   icon: '🎉', value: 'red' },
      ],
      reactions: { green: "La qualité pas la quantité. Pareil pour moi 😌", neutral: "Ok. Tant que c'est de la vraie amitié.", red: "Beaucoup de connaissances, peu de profondeur souvent…" },
    },
  ],
  endings: {
    smash: { emoji: '😮', text: "Franchement… t'es quelqu'un de sérieux·se. Ça se voit pas souvent. On se revoit." },
    high:  { emoji: '🥰', text: "C'était vraiment bien. T'es quelqu'un de bien." },
    mid:   { emoji: '🤔', text: "T'as des qualités mais j'suis pas sûre qu'on soit vraiment alignés." },
    low:   { emoji: '😬', text: "Je pense qu'on cherche pas les mêmes choses." },
    pass:  { emoji: '🚩', text: "Non. Je veux pas perdre mon temps." },
  },
},

/* ════════════════════════════════════════
   RACHEL — Cultivée, indépendante, forte identité
══════════════════════════════════════════ */
{
  id: 'rachel',
  gender: 'f',
  name: 'Rachel',
  age: 24,
  emoji: '✡️',
  avatar: 'linear-gradient(135deg, #3a1c71 0%, #d76d77 50%, #ffaf7b 100%)',
  bio: 'Droit international, debates, Shabbat en famille. Cherche quelqu\'un de vrai, pas de superficiel.',
  vibe: '📚 Intellectuelle & enracinée',
  flags: {
    'Identité culturelle forte': 'green',
    'Très intellectuelle':       'green',
    'Exigeante':                 'neutral',
    'Famille importante':        'green',
    'Piquante à l\'oral':        'neutral',
    'Droite dans ses bottes':    'green',
    'Peu patiente avec la bêtise': 'red',
    'Romantique discrète':       'green',
  },
  warn3red:    "Écoute… je pense qu'on est pas au même niveau de profondeur. Et c'est important pour moi 🙄",
  smash3green: "Je savais pas que ce date allait être aussi stimulant. T'es rare. Vraiment 😊",
  questions: [
    { type: 'choice', text: "Les débats d'idées, la politique, l'histoire — ça t'intéresse ou ça t'ennuie ?", topic: 'Très intellectuelle',
      choices: [
        { label: "J'adore débattre et m'informer",         icon: '🗣️', value: 'green' },
        { label: "Ça m'intéresse si c'est pas trop intense", icon: '🤔', value: 'neutral' },
        { label: "Je préfère les sujets plus légers",       icon: '😅', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui a un cerveau actif. C'est appréciable 😌", neutral: "« Pas trop intense »… c'est quand même une limite 😅", red: "Les sujets légers. Ok. On n'aura pas de conversations profondes alors." },
    },
    { type: 'flag', text: "« Je fête le Shabbat en famille chaque vendredi »", topic: 'Identité culturelle forte', correct: 'green',
      reactions: { good: "Les rituels familiaux c'est ce qui construit une identité solide 😌", neutral: "T'as l'air mitigé(e)… 🤔", bad: "Ça te semble bizarre ? C'est juste une tradition familiale." },
    },
    { type: 'choice', text: "Quelqu'un dit une énorme bêtise en société. Tu fais quoi ?", topic: 'Peu patiente avec la bêtise',
      choices: [
        { label: "Je la corrige poliment mais fermement",   icon: '✋', value: 'green' },
        { label: "Je laisse passer si c'est sans gravité",  icon: '😌', value: 'neutral' },
        { label: "Je dis rien, c'est pas mon rôle",         icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Bien. Laisser la bêtise circuler c'est l'approuver silencieusement.", neutral: "Dépend de la bêtise en question… j'accepte.", red: "« Pas mon rôle »… vision très confortable ça." },
    },
    { type: 'flag', text: "« Mon identité c'est pas juste religieux, c'est culturel, historique, familial »", topic: 'Identité culturelle forte', correct: 'green',
      reactions: { good: "La nuance entre religion et culture c'est essentiel. T'as compris 😌", neutral: "T'as l'air de pas trop savoir quoi penser de ça 😅", bad: "C'est trop compliqué pour toi peut-être 😐" },
    },
    { type: 'choice', text: "T'es comment quand tu veux vraiment quelque chose ?", topic: 'Exigeante',
      choices: [
        { label: "Déterminé(e), je lâche pas",            icon: '🎯', value: 'green' },
        { label: "Je m'adapte selon les obstacles",       icon: '😌', value: 'neutral' },
        { label: "Assez flexible sur mes objectifs",      icon: '🤷', value: 'red' },
      ],
      reactions: { green: "La détermination c'est ce qui sépare ceux qui font de ceux qui rêvent.", neutral: "S'adapter c'est bien. Capituler trop vite c'est autre chose.", red: "Très flexible… ça veut dire que rien compte vraiment assez ?" },
    },
    { type: 'flag', text: "« Je me bats pour mes opinions mais je sais aussi changer d'avis »", topic: 'Droite dans ses bottes', correct: 'green',
      reactions: { good: "L'intelligence c'est ça : avoir des convictions ET savoir les remettre en question 😌", neutral: "Pas très convaincu(e) 🤔", bad: "Tu valorises pas ça ? Dommage." },
    },
    { type: 'choice', text: "Amour et intelligence émotionnelle, c'est lié pour toi ?", topic: 'Romantique discrète',
      choices: [
        { label: "Totalement, c'est la base d'une vraie relation", icon: '❤️', value: 'green' },
        { label: "Important mais pas suffisant seul",              icon: '🤔', value: 'neutral' },
        { label: "Je suis plus pragmatique que romantique",        icon: '😐', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui sait ce qu'il/elle cherche vraiment 😌", neutral: "Pas faux. Mais sans ça on reste en surface.", red: "Très pragmatique. On verra si ça suffit." },
    },
    { type: 'flag', text: "« Je lis beaucoup, j'aime les musées, les expos »", topic: 'Très intellectuelle', correct: 'green',
      reactions: { good: "On peut passer nos dates dans des musées alors 😌", neutral: "Pas trop ton truc apparemment 🤔", bad: "Lecteur·ice et musées c'est nul pour toi ? Ok." },
    },
  ],
  endings: {
    smash: { emoji: '✨', text: "Ok je savais pas que ce rendez-vous allait être aussi stimulant intellectuellement. On refait ça quand ?" },
    high:  { emoji: '🥰', text: "T'es quelqu'un de bien. Vraiment. Ce date était agréable." },
    mid:   { emoji: '🤔', text: "T'as des qualités indéniables. Mais on n'est pas sur la même longueur d'onde." },
    low:   { emoji: '😬', text: "On a des profils vraiment différents. Je le sens." },
    pass:  { emoji: '🚩', text: "Non. T'as pas la profondeur que je recherche." },
  },
},

/* ════════════════════════════════════════
   JADE — Ultra féministe & activiste
══════════════════════════════════════════ */
{
  id: 'jade',
  gender: 'f',
  name: 'Jade',
  age: 25,
  emoji: '✊',
  avatar: 'linear-gradient(135deg, #f953c6 0%, #b91d73 100%)',
  bio: 'Militante féministe, militante éco. Si tu peux pas nommer le patriarcat, on aura un problème.',
  vibe: '✊ Militante & engagée',
  flags: {
    'Très engagée politiquement': 'neutral',
    'Intransigeante':             'red',
    'Intellectuellement stimulante': 'green',
    'Cohérente avec ses valeurs': 'green',
    'Peu de recul parfois':       'red',
    'Passionnée':                 'green',
    'Exigeante envers les autres': 'red',
    'Sincère':                    'green',
  },
  warn3red:    "Je pense qu'on est clairement pas alignés sur les valeurs. Et ça c'est rédhibitoire pour moi.",
  smash3green: "Ok là je m'attendais vraiment pas à ça. T'es conscient·e et ça se sent. C'est rare 🔥",
  questions: [
    { type: 'choice', text: "Le féminisme, pour toi c'est quoi ?", topic: 'Très engagée politiquement',
      choices: [
        { label: "L'égalité des droits, j'y crois pleinement",   icon: '✊', value: 'green' },
        { label: "Je suis pour l'égalité mais le mot me pèse",   icon: '🤔', value: 'neutral' },
        { label: "Je pense qu'on est allés trop loin",           icon: '😐', value: 'red' },
      ],
      reactions: { green: "Bien. C'est le minimum mais c'est déjà quelque chose.", neutral: "Le mot te pèse mais pas les inégalités ? C'est intéressant comme hiérarchie.", red: "« Trop loin. » Tu peux développer ça sans te planter ?" },
    },
    { type: 'flag', text: "« Je fais attention à pas couper la parole aux femmes dans une conversation »", topic: 'Cohérente avec ses valeurs', correct: 'green',
      reactions: { good: "L'attention aux dynamiques de groupe c'est un signe de maturité 😌", neutral: "Pas très convaincu(e) 🤔", bad: "Tu trouves ça exagéré ? 🙄" },
    },
    { type: 'choice', text: "Je vais à des manifs, je signe des pétitions, j'ai des autocollants partout. Ça te dérange ?", topic: 'Très engagée politiquement',
      choices: [
        { label: "Non, l'engagement c'est admirable",        icon: '🙌', value: 'green' },
        { label: "C'est bien tant que c'est pas envahissant", icon: '😅', value: 'neutral' },
        { label: "Franchement c'est un peu trop pour moi",   icon: '😐', value: 'red' },
      ],
      reactions: { green: "Au moins t'as pas peur de quelqu'un qui a des convictions 😌", neutral: "« Envahissant »… c'est quoi le seuil ? Les injustices elles le sont pas un peu elles aussi ?", red: "Trop. Comme beaucoup de choses qui dérangent je suppose." },
    },
    { type: 'flag', text: "« J'ai du mal à accepter quelqu'un qui ne remet pas ses privilèges en question »", topic: 'Exigeante envers les autres', correct: 'red',
      reactions: { good: "Exactement. La remise en question c'est la base.", neutral: "T'es pas très convaincu(e) là 🤔", bad: "Trop exigeant(e) pour toi ? C'est pourtant le minimum." },
    },
    { type: 'choice', text: "Congé parental, tâches ménagères — t'es comment sur le partage ?", topic: 'Cohérente avec ses valeurs',
      choices: [
        { label: "50/50 sans discussion, c'est évident",         icon: '⚖️', value: 'green' },
        { label: "J'essaie mais c'est pas toujours parfait",     icon: '😅', value: 'neutral' },
        { label: "Ça dépend des compétences de chacun",          icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Voilà un équilibre sain. C'est rare et précieux.", neutral: "Au moins t'es honnête. On peut travailler là-dessus.", red: "« Compétences de chacun »… biais très pratique pour celui qui fait moins." },
    },
    { type: 'flag', text: "« Je consomme de façon éco-responsable »", topic: 'Sincère', correct: 'green',
      reactions: { good: "La cohérence actes/valeurs c'est l'essentiel 😌", neutral: "Mouais… 🤔", bad: "Pas de cohérence là-dessus ? Dommage." },
    },
    { type: 'choice', text: "J'ai des opinions tranchées. Ça peut piquer parfois. T'es ok avec ça ?", topic: 'Intransigeante',
      choices: [
        { label: "Oui, j'aime les gens qui ont des convictions",   icon: '💪', value: 'green' },
        { label: "Tant que tu sais écouter aussi",                 icon: '🤝', value: 'neutral' },
        { label: "Non j'aime pas les conflits",                    icon: '😅', value: 'red' },
      ],
      reactions: { green: "Bien. Les opinions molles c'est pas mon truc.", neutral: "J'écoute. Mais je change pas d'avis juste pour plaire.", red: "Les conflits ? Ou les désaccords ? C'est pas pareil." },
    },
    { type: 'flag', text: "« Je peux reconnaître quand j'ai tort »", topic: 'Peu de recul parfois', correct: 'green',
      reactions: { good: "L'humilité intellectuelle c'est la marque des gens vraiment intelligents 😌", neutral: "Réponse modérée 🤔", bad: "C'est une qualité de le reconnaître pourtant." },
    },
  ],
  endings: {
    smash: { emoji: '✊', text: "Ok. T'es conscient·e, t'as des valeurs et tu les défends. J'attendais ça." },
    high:  { emoji: '🥰', text: "C'était vraiment stimulant. T'es pas parfait(e) mais t'es sincère et ça compte beaucoup." },
    mid:   { emoji: '🤔', text: "On a des points communs mais des divergences qui vont créer de la friction." },
    low:   { emoji: '😬', text: "Je pense qu'on voit le monde vraiment différemment." },
    pass:  { emoji: '🚩', text: "Non. On n'est pas alignés et pour moi les valeurs c'est pas négociable." },
  },
},

/* ════════════════════════════════════════
   ELSA — Équitation & entourage masculin
══════════════════════════════════════════ */
{
  id: 'elsa',
  gender: 'f',
  name: 'Elsa',
  age: 20,
  emoji: '🐎',
  avatar: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
  bio: 'Cavalière compétition, passion cheval depuis 8 ans. La plupart de mes amis sont des mecs, ask me why 🤷',
  vibe: '🐎 Équitation & amis garçons',
  flags: {
    'Passion équitation':         'green',
    'Majorité d\'amis mecs':      'red',
    'Indépendante':               'green',
    'Patiente avec les animaux':  'green',
    'Trop proche de certains amis': 'red',
    'Naturelle et directe':       'green',
    'Pas drama':                  'green',
    'Frontières floues':          'red',
  },
  warn3red:    "Ok je sens que t'es du genre à mal le vivre que j'aie autant d'amis garçons… c'est un problème 😅",
  smash3green: "T'es vraiment à l'aise avec qui je suis. C'est tellement rare, la confiance 🐎",
  questions: [
    { type: 'choice', text: "Je passe 3h au centre équestre plusieurs fois par semaine. Le cheval c'est ma vie. T'en penses quoi ?", topic: 'Passion équitation',
      choices: [
        { label: "Une passion forte c'est très attirant",      icon: '🐎', value: 'green' },
        { label: "Ok tant que t'as du temps libre aussi",      icon: '😌', value: 'neutral' },
        { label: "Ça fait beaucoup quand même",                icon: '😬', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui respecte les passions absorbantes, j'aime 😌", neutral: "J'aurai du temps, mais le cheval passera avant certaines choses, c'est honnête.", red: "Beaucoup ? C'est juste ma vie 😅" },
    },
    { type: 'flag', text: "« La plupart de mes meilleurs amis sont des garçons »", topic: 'Majorité d\'amis mecs', correct: 'red',
      reactions: { good: "Au moins t'es lucide que ça peut être un sujet 😅", neutral: "T'as une opinion là-dessus mais tu l'assumes pas trop 🤔", bad: "Ça te dérange vraiment pas ? C'est rare." },
    },
    { type: 'choice', text: "Mon meilleur ami m'appelle tous les soirs. T'en penses quoi ?", topic: 'Frontières floues',
      choices: [
        { label: "C'est une amitié forte, pas de souci",      icon: '🤝', value: 'green' },
        { label: "Je poserai une ou deux questions",          icon: '🤔', value: 'neutral' },
        { label: "Tous les soirs c'est trop, ça m'embêterait", icon: '😬', value: 'red' },
      ],
      reactions: { green: "Confiance totale. C'est exactement ça. Merci 😌", neutral: "Questions honnêtes, j'accepte. Tant que c'est pas du contrôle.", red: "C'est une amitié de longue date. Ça se respecte." },
    },
    { type: 'flag', text: "« Je suis jamais dépendante affectivement »", topic: 'Indépendante', correct: 'green',
      reactions: { good: "L'indépendance dans une relation c'est ce qui la rend saine 😌", neutral: "T'es mitigé(e) là-dessus ? 🤔", bad: "T'aimes les gens dépendants ? Curieux." },
    },
    { type: 'choice', text: "Une compétition équestre ça dure tout le weekend. Tu viens soutenir ou tu restes chez toi ?", topic: 'Passion équitation',
      choices: [
        { label: "Je viens voir, ça m'intéresse de découvrir", icon: '🏟️', value: 'green' },
        { label: "Une fois oui, mais pas à chaque fois",       icon: '😌', value: 'neutral' },
        { label: "C'est pas vraiment mon truc",                icon: '😅', value: 'red' },
      ],
      reactions: { green: "T'es curieux·se et présent(e). C'est exactement ce que je veux 😌", neutral: "Honnête. Je demanderai pas à chaque fois.", red: "Ok… j'irai seule alors 😅" },
    },
    { type: 'flag', text: "« Je drama pas, je règle les problèmes calmement »", topic: 'Pas drama', correct: 'green',
      reactions: { good: "Hyper important pour moi. J'aime les gens directs et calmes 😌", neutral: "Mouais 🤔", bad: "Tu préfères le drama ? Ah." },
    },
    { type: 'choice', text: "La jalousie dans un couple, t'en es où là-dessus ?", topic: 'Trop proche de certains amis',
      choices: [
        { label: "Zéro jalousie si la confiance est là",        icon: '😌', value: 'green' },
        { label: "Un peu de jalousie c'est humain",             icon: '🤔', value: 'neutral' },
        { label: "Je suis assez jaloux·se honnêtement",         icon: '🔥', value: 'red' },
      ],
      reactions: { green: "C'est exactement ça. La jalousie sans confiance c'est de la toxicité.", neutral: "Tant que ça reste léger et pas contrôlant.", red: "Avec mon entourage… ça va être compliqué 😬" },
    },
    { type: 'choice', text: "Un cheval c'est comme un être humain pour moi. T'aimes les animaux ?", topic: 'Patiente avec les animaux',
      choices: [
        { label: "Oui, je comprends ce lien",         icon: '🐾', value: 'green' },
        { label: "Je les aime bien de loin",          icon: '😅', value: 'neutral' },
        { label: "Non, je suis pas trop animaux",     icon: '🙅', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui comprend le lien humain-animal. Rare 😌", neutral: "De loin… faudra faire des efforts avec mon cheval alors 😂", red: "Ah. C'est une partie importante de ma vie ça…" },
    },
  ],
  endings: {
    smash: { emoji: '🐎', text: "T'as aucun problème avec qui je suis. C'est tellement rare. Je veux te revoir." },
    high:  { emoji: '🥰', text: "C'était vraiment chouette. T'es cool et à l'aise avec ma vie. J'apprécie." },
    mid:   { emoji: '🤔', text: "T'as des qualités mais je sens que mon entourage te poserait problème." },
    low:   { emoji: '😬', text: "Je pense que tu pourrais pas gérer mes amitiés et mon emploi du temps." },
    pass:  { emoji: '🚩', text: "Non. Tu supporterais pas ma vie et j'ai pas envie de la changer." },
  },
},

/* ════════════════════════════════════════
   ELISOU — Toxique, piano, piercing, handball
══════════════════════════════════════════ */
{
  id: 'elisou',
  gender: 'f',
  name: 'Élisou',
  age: 19,
  emoji: '💿',
  avatar: 'linear-gradient(135deg, #6a3093 0%, #a044ff 100%)',
  bio: 'Pianiste le matin, handballeuse l\'aprèm, injoignable la nuit. Piercing septum et âme sensible cachée.',
  vibe: '🎹 Artiste & sportive, un peu folle',
  flags: {
    'Pianiste':               'green',
    'Handballeuse':           'green',
    'Comportements toxiques': 'red',
    'Piercing/style perso':   'neutral',
    'Très sympa':             'green',
    'Émotionnellement imprévisible': 'red',
    'Créative':               'green',
    'Dépendance affective':   'red',
  },
  warn3red:    "Ok je vais être honnête : tu me ressembles pas assez. Et quand ça me ressemble pas, ça dure pas 😌",
  smash3green: "Attends t'es vraiment incroyable toi… j'aurais jamais cru matcher autant avec quelqu'un 🎹",
  questions: [
    { type: 'choice', text: "Je joue du piano depuis mes 7 ans. La musique c'est viscéral pour moi. T'as un rapport avec un art toi ?", topic: 'Pianiste',
      choices: [
        { label: "Oui, j'ai aussi une pratique artistique",       icon: '🎨', value: 'green' },
        { label: "J'admire les gens qui pratiquent un art",       icon: '👏', value: 'neutral' },
        { label: "L'art c'est pas vraiment mon truc",             icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui crée aussi, on va se comprendre 🎹", neutral: "L'admiration c'est bien mais t'aurais dû te lancer toi aussi 😌", red: "Ah… on aura pas ce truc en commun alors." },
    },
    { type: 'flag', text: "« Je fais parfois des choses que je regrette pour attirer l'attention »", topic: 'Comportements toxiques', correct: 'red',
      reactions: { good: "Au moins t'es lucide là-dessus. C'est un vrai red flag mais au moins t'en parles.", neutral: "T'as une réaction mitiguée là 🤔", bad: "Tu normalises ça ? C'est inquiétant." },
    },
    { type: 'choice', text: "J'ai le septum percé, des piercings aux oreilles. L'apparence alternative ça te dit quoi ?", topic: 'Piercing/style perso',
      choices: [
        { label: "J'aime les gens qui assument leur style",  icon: '💎', value: 'green' },
        { label: "L'apparence c'est secondaire pour moi",   icon: '😌', value: 'neutral' },
        { label: "C'est pas vraiment mon esthétique",       icon: '🤷', value: 'red' },
      ],
      reactions: { green: "L'assurance dans son style c'est tellement attractif 😌", neutral: "Secondaire… ok. Tant que c'est pas négatif.", red: "T'es pas obligé(e) d'aimer mais moi c'est pas près de changer 😅" },
    },
    { type: 'flag', text: "« Je joue en National 2 de handball »", topic: 'Handballeuse', correct: 'green',
      reactions: { good: "National 2 c'est sérieux. T'as du respect pour ça 💪", neutral: "Réponse modérée 🤔", bad: "Le sport de haut niveau ça t'impressionne pas ? Ok." },
    },
    { type: 'choice', text: "Parfois je disparais quelques jours sans donner de nouvelles. T'aurais quelle réaction ?", topic: 'Émotionnellement imprévisible',
      choices: [
        { label: "Je respecte le besoin de solitude",          icon: '😌', value: 'green' },
        { label: "Je vérifie une fois que tout va bien",       icon: '🤔', value: 'neutral' },
        { label: "Ça m'inquièterait ou m'énèrverait beaucoup", icon: '😬', value: 'red' },
      ],
      reactions: { green: "Tu me fais confiance sans te perdre. C'est parfait 😌", neutral: "Un message c'est ok. Juste un.", red: "Je suis pas une disparition… juste besoin d'air parfois 😅" },
    },
    { type: 'flag', text: "« Je peux être hyper sympa et me retourner contre quelqu'un très vite »", topic: 'Comportements toxiques', correct: 'red',
      reactions: { good: "T'as bien vu que c'est une chose sur laquelle je dois bosser.", neutral: "T'as pas de position claire là 🤔", bad: "Tu trouves ça normal ? 😬" },
    },
    { type: 'choice', text: "Piano classique, jazz, composition perso — tu peux supporter d'écouter ça souvent ?", topic: 'Pianiste',
      choices: [
        { label: "Oui j'adore, c'est beau",             icon: '🎵', value: 'green' },
        { label: "De temps en temps avec plaisir",      icon: '😌', value: 'neutral' },
        { label: "Je préfère la musique plus rythmée",  icon: '🎧', value: 'red' },
      ],
      reactions: { green: "On fera des soirées musique alors 🎹", neutral: "De temps en temps c'est ok. Je me calme parfois.", red: "T'es pas obligé(e) d'être là quand je joue 😌" },
    },
    { type: 'flag', text: "« Je suis vraiment quelqu'un de bien quand je vais bien »", topic: 'Très sympa', correct: 'neutral',
      reactions: { good: "La condition « quand je vais bien » c'est honnête mais c'est un vrai sujet 😌", neutral: "T'as bien vu la nuance.", bad: "T'aurais dû relever cette nuance." },
    },
  ],
  endings: {
    smash: { emoji: '🎹', text: "T'as vu qui je suis vraiment — le bon et le moins bon — et t'es toujours là. C'est ça qui compte." },
    high:  { emoji: '🥰', text: "C'était trop bien. T'as pas eu peur de moi, j'aime ça." },
    mid:   { emoji: '🤔', text: "T'es bien… mais je sais pas si tu pourrais gérer ma complexité sur la durée." },
    low:   { emoji: '😬', text: "Je pense que tu serais épuisé(e) avec moi après 2 semaines." },
    pass:  { emoji: '🚩', text: "Non. On est trop différents et j'me vois pas m'adapter." },
  },
},

/* ════════════════════════════════════════
   CILLIAN — Aime les avions, les hommes (discret), bro attitude
══════════════════════════════════════════ */
{
  id: 'cillian',
  gender: 'm',
  name: 'Cillian',
  age: 22,
  emoji: '✈️',
  avatar: 'linear-gradient(135deg, #373b44 0%, #4286f4 100%)',
  bio: 'Passionné d\'aviation, admin Discord, suit trop de réseaux. Pense être mystérieux alors qu\'il est lisible.',
  vibe: '✈️ Aviation & vibes entre potes',
  flags: {
    'Passion aviation':        'green',
    'Discord / réseaux':       'neutral',
    'Bro mentality':           'red',
    'Discret sur lui-même':    'neutral',
    'Pose au dur':             'red',
    'Loyal envers ses proches': 'green',
    'Mauvaise écoute':         'red',
    'Curieux de tout':         'green',
  },
  warn3red:    "Ouais non… tu corresponds pas à l'énergie que je cherche. C'est bon.",
  smash3green: "Wah… toi t'es vraiment different des autres. C'est cool 👀",
  questions: [
    { type: 'choice', text: "L'aviation c'est ma passion numéro 1. Décollages, simulateurs, histoire de l'air… ça t'intéresse ?", topic: 'Passion aviation',
      choices: [
        { label: "Carrément, je trouve ça fascinant",     icon: '✈️', value: 'green' },
        { label: "Pas fan mais je peux écouter",          icon: '😌', value: 'neutral' },
        { label: "Non, absolument pas mon truc",          icon: '😴', value: 'red' },
      ],
      reactions: { green: "Bien. On peut parler de ça des heures 😅", neutral: "Écouter c'est déjà beaucoup.", red: "Ok… j'en parlerai moins alors." },
    },
    { type: 'flag', text: "« Je suis admin de 3 serveurs Discord »", topic: 'Discord / réseaux', correct: 'neutral',
      reactions: { good: "Respect… enfin un peu 😅", neutral: "T'as pas d'avis là-dessus 🤔", bad: "C'est négatif pour toi ? C'est de la gestion de comm'." },
    },
    { type: 'choice', text: "Je traîne surtout avec mes potes, on fait nos trucs entre nous. T'es comment socialement toi ?", topic: 'Bro mentality',
      choices: [
        { label: "J'aime aussi avoir mon cercle proche",       icon: '🤝', value: 'green' },
        { label: "Je m'adapte aux gens que je rencontre",      icon: '😌', value: 'neutral' },
        { label: "J'aime rencontrer plein de nouvelles têtes", icon: '🎉', value: 'red' },
      ],
      reactions: { green: "Ouais respect. Le cercle fermé c'est plus sûr.", neutral: "L'adaptabilité c'est une qualité en fait.", red: "Plein de nouvelles têtes… t'es pas fatigué ? 😅" },
    },
    { type: 'flag', text: "« Je follow 800 personnes sur Instagram mais je connais vraiment 10 personnes »", topic: 'Discord / réseaux', correct: 'red',
      reactions: { good: "Au moins t'as vu le problème toi-même 😅", neutral: "Mitigé(e) 🤔", bad: "Tu trouves ça sain toi ?" },
    },
    { type: 'choice', text: "T'es quelqu'un de direct ou plutôt réservé sur toi-même ?", topic: 'Discret sur lui-même',
      choices: [
        { label: "Direct, j'aime qu'on se connaisse vite",       icon: '🗣️', value: 'green' },
        { label: "Je m'ouvre avec le temps",                     icon: '😌', value: 'neutral' },
        { label: "Je garde toujours une part de mystère",        icon: '🕵️', value: 'red' },
      ],
      reactions: { green: "Ok t'es à l'aise. C'est bien.", neutral: "Ça vient avec la confiance, j'entends.", red: "Le mystère c'est bien dans les films, pas dans les relations 😅" },
    },
    { type: 'flag', text: "« J'écoute bien les autres sauf quand j'ai une meilleure idée »", topic: 'Mauvaise écoute', correct: 'red',
      reactions: { good: "Ouais… c'est honnête d'avouer ça en tout cas.", neutral: "Mouais 🤔", bad: "Tu trouves ça ok ?" },
    },
    { type: 'choice', text: "Un long voyage en avion t'attire ou te terrifie ?", topic: 'Passion aviation',
      choices: [
        { label: "J'adore, les voyages c'est magique",      icon: '🌍', value: 'green' },
        { label: "Ça va tant que c'est pas trop long",      icon: '😌', value: 'neutral' },
        { label: "Je supporte pas d'être en avion",         icon: '😨', value: 'red' },
      ],
      reactions: { green: "Ok on peut voyager ensemble alors 😌", neutral: "Combien d'heures t'acceptes ? J'ai besoin de savoir 😅", red: "Ah. C'est un problème avec moi ça…" },
    },
    { type: 'flag', text: "« Je suis loyal à ceux qui me sont fidèles »", topic: 'Loyal envers ses proches', correct: 'green',
      reactions: { good: "La loyauté réciproque c'est la base de tout 😌", neutral: "Mitigé(e) 🤔", bad: "T'es pas attiré(e) par les gens loyaux ?" },
    },
    { type: 'choice', text: "Je pose parfois au mystérieux alors que j'ai juste rien à dire 😅 T'aimes les gens authentiques ?", topic: 'Pose au dur',
      choices: [
        { label: "Oui, l'authenticité c'est ce que je cherche",  icon: '😌', value: 'green' },
        { label: "Ça dépend, le mystère peut être fun",          icon: '🤔', value: 'neutral' },
        { label: "J'aime bien le côté secret chez quelqu'un",   icon: '😏', value: 'red' },
      ],
      reactions: { green: "Bien. Je vais essayer d'être plus authentique alors 😅", neutral: "Le mystère ok mais là c'est de la façade, honnêtement.", red: "T'aimes le mystère ? Je vais en rajouter alors 😅" },
    },
  ],
  endings: {
    smash: { emoji: '✈️', text: "Ok t'es vraiment bien. Toi et moi on s'entend bien, ça se sent." },
    high:  { emoji: '🥰', text: "C'était cool. T'es authentique et ça change des autres." },
    mid:   { emoji: '🤔', text: "On a des points communs mais des trucs qui collent pas trop." },
    low:   { emoji: '😬', text: "Ouais… je vois pas vraiment ça marcher entre nous." },
    pass:  { emoji: '🚩', text: "Non vraiment pas. On est pas compatibles." },
  },
},

/* ════════════════════════════════════════
   LÉONIE — Tennis, TikTok, chiante socialement
══════════════════════════════════════════ */
{
  id: 'leonie',
  gender: 'f',
  name: 'Léonie',
  age: 21,
  emoji: '🎾',
  avatar: 'linear-gradient(135deg, #f7ff00 0%, #db36a4 100%)',
  bio: 'Tennis le weekend, TikTok le reste du temps. On me dit que je suis chiante mais je vois pas pourquoi 🤷',
  vibe: '📱 TikTok & tennis, très sûre d\'elle',
  flags: {
    'Tennis':                   'green',
    'Accro TikTok':             'red',
    'Socialement difficile':    'red',
    'Interrompt les gens':      'red',
    'Sûre d\'elle à l\'excès':  'red',
    'Belle énergie physique':   'green',
    'Peu d\'écoute':            'red',
    'Drôle malgré tout':        'green',
  },
  warn3red:    "Ok genre… tu réponds vraiment pas bien à mes questions là. C'est bizarre 🙄",
  smash3green: "Attends t'es vraiment pas chiant(e) toi. Je m'attendais pas à ça 😳",
  questions: [
    { type: 'choice', text: "Je passe genre 4-5h sur TikTok par jour. C'est un problème pour toi ?", topic: 'Accro TikTok',
      choices: [
        { label: "Honnêtement oui, c'est beaucoup",              icon: '😬', value: 'green' },
        { label: "Tant que t'es présente quand on est ensemble", icon: '😌', value: 'neutral' },
        { label: "Moi aussi j'y passe du temps",                 icon: '📱', value: 'red' },
      ],
      reactions: { green: "Ok genre t'as pas tort mais c'est ma détente 🙄", neutral: "Je suis présente quand je veux bien oui 😌", red: "Ah parfait on peut scroller ensemble alors 😂" },
    },
    { type: 'flag', text: "« Je joue au tennis en interclub niveau 15/4 »", topic: 'Tennis', correct: 'green',
      reactions: { good: "Là au moins tu vois que le sport c'est sérieux pour moi 😌", neutral: "T'as pas l'air impressionné(e) 🤔", bad: "15/4 c'est bon niveau… tu sais pas ce que c'est ? 🙄" },
    },
    { type: 'choice', text: "Je coupe souvent les gens quand ils parlent parce que j'ai quelque chose d'important à dire. T'as quel rapport à ça ?", topic: 'Interrompt les gens',
      choices: [
        { label: "C'est un truc qui me dérange franchement",          icon: '😐', value: 'green' },
        { label: "Je fais pareil parfois, on est humains",            icon: '🤷', value: 'neutral' },
        { label: "Si c'est important faut le dire ouais",             icon: '😄', value: 'red' },
      ],
      reactions: { green: "Ok genre t'as raison mais je m'en rends pas toujours compte 😅", neutral: "Voilà au moins t'es honnête.", red: "Exactement ! Merci quelqu'un qui comprend 😂" },
    },
    { type: 'flag', text: "« Je me suis disputée avec ma prof, mon chef et ma meilleure amie ce mois-ci »", topic: 'Socialement difficile', correct: 'red',
      reactions: { good: "Oui bon… j'ai un problème avec l'autorité et les gens qui ont tort.", neutral: "Mitigé(e) là 🤔", bad: "T'as rien vu de bizarre dans ça ?" },
    },
    { type: 'choice', text: "Mon dernier TikTok a fait 200k vues. C'est important pour moi. Tu penses quoi de la validation en ligne ?", topic: 'Sûre d\'elle à l\'excès',
      choices: [
        { label: "La validation numérique c'est pas grand chose",      icon: '😐', value: 'green' },
        { label: "C'est cool si tu kiffes créer du contenu",           icon: '😌', value: 'neutral' },
        { label: "200k respect, c'est stylé !",                        icon: '🔥', value: 'red' },
      ],
      reactions: { green: "Genre… t'as quand même pas besoin de me rabaisser là 😤", neutral: "Ouais je kiffe créer, merci de le voir 😌", red: "Voilà une bonne réponse enfin 😂" },
    },
    { type: 'flag', text: "« Je sais que je suis chiante mais je vois pas le problème »", topic: 'Peu d\'écoute', correct: 'red',
      reactions: { good: "Exactement c'est un problème de l'accepter sans chercher à changer.", neutral: "Réponse safe 😅", bad: "Tu trouves ça ok toi ? Vraiment ?" },
    },
    { type: 'choice', text: "T'as un avis sur quelque chose. Je t'interromps pour dire le mien. Tu réagis comment ?", topic: 'Peu d\'écoute',
      choices: [
        { label: "Je te le dis clairement, c'est irrespectueux",       icon: '✋', value: 'green' },
        { label: "Je laisse passer la première fois",                  icon: '😌', value: 'neutral' },
        { label: "Je continue par-dessus toi aussi",                  icon: '😂', value: 'red' },
      ],
      reactions: { green: "Ok ok j'entends le message… j'essaierai 😅", neutral: "Bien. La première fois. Faudra pas trop de premières fois.", red: "PTDR la guerre des mots qu'on aurait 😂" },
    },
    { type: 'flag', text: "« Je fais rire même les gens que j'énerve »", topic: 'Drôle malgré tout', correct: 'green',
      reactions: { good: "Ouais c'est mon superpouvoir, j'avoue 😂", neutral: "T'as du mal à y croire 🤔", bad: "T'as jamais été tenu(e) en haleine par quelqu'un d'énervant mais drôle ?" },
    },
  ],
  endings: {
    smash: { emoji: '😳', text: "Attends t'es vraiment pas chiant(e) toi. Je savais pas qu'un date pouvait être aussi bien." },
    high:  { emoji: '🥰', text: "Ok t'es sympa. C'était bien. Même si t'as dit des trucs que j'aime pas 😂" },
    mid:   { emoji: '🤔', text: "Ouais bof… on est pas sur la même longueur d'onde honnêtement." },
    low:   { emoji: '😬', text: "Je pense que tu me trouves trop chiante. C'est réciproque du coup 😅" },
    pass:  { emoji: '🚩', text: "Non. T'as clairement aucun humour. Au revoir." },
  },
},

/* ════════════════════════════════════════
   SECUROSERV — Possessif, jaloux, peu de charisme
══════════════════════════════════════════ */
{
  id: 'securoserv',
  gender: 'm',
  name: 'Kévin',
  age: 24,
  emoji: '🔒',
  avatar: 'linear-gradient(135deg, #485563 0%, #29323c 100%)',
  bio: 'Agent de sécurité. J\'aime savoir où sont les gens que j\'aime. C\'est pas de la jalousie, c\'est de l\'amour.',
  vibe: '🔒 Protecteur… ou possessif ?',
  flags: {
    'Possessif':                 'red',
    'Jaloux':                    'red',
    'Peu de charisme':           'red',
    'Gênant en société':         'red',
    'Loyal':                     'green',
    'Sincère dans ses sentiments': 'green',
    'Contrôlant':                'red',
    'Peur de l\'abandon':        'red',
  },
  warn3red:    "Ok… j'aime pas ton attitude. T'es trop indépendant(e). Ça me convient pas.",
  smash3green: "Tu me rassures vraiment toi. T'es différent(e). Je pense qu'avec toi ça pourrait vraiment marcher 😌",
  questions: [
    { type: 'choice', text: "Moi j'aime savoir où est la personne avec qui je suis. C'est rassurant. T'es ok avec ça ?", topic: 'Possessif',
      choices: [
        { label: "Non, j'ai besoin de mon espace",             icon: '✋', value: 'green' },
        { label: "Ça dépend dans quel sens tu l'entends",      icon: '🤔', value: 'neutral' },
        { label: "Ça me paraît normal de se tenir au courant", icon: '📍', value: 'red' },
      ],
      reactions: { green: "Ton espace… t'as tellement d'espace que tu partages rien ?", neutral: "Dans le bon sens c'est du soin. Je fais que du soin.", red: "Voilà quelqu'un de raisonnable 😌" },
    },
    { type: 'flag', text: "« Je vérifie parfois le téléphone de mes ex »", topic: 'Jaloux', correct: 'red',
      reactions: { good: "Ok je sais que c'est pas ouf… mais je contrôle pas tout.", neutral: "T'as pas d'avis tranché là 🤔", bad: "T'as pas vu le problème ?" },
    },
    { type: 'choice', text: "Quelqu'un que t'aimes a un·e ami·e très proche du sexe opposé. T'en penses quoi ?", topic: 'Jaloux',
      choices: [
        { label: "Aucun problème si la confiance est là",           icon: '😌', value: 'green' },
        { label: "Je demanderai qui c'est et comment ils se sont connus", icon: '🤔', value: 'neutral' },
        { label: "J'aimerais qu'ils se voient moins souvent",       icon: '🔥', value: 'red' },
      ],
      reactions: { green: "T'as l'air très confiant(e). Peut-être trop.", neutral: "Poser des questions c'est normal, c'est de la curiosité.", red: "Je comprends. La proximité ça crée des situations." },
    },
    { type: 'flag', text: "« Je téléphone plusieurs fois si on répond pas »", topic: 'Contrôlant', correct: 'red',
      reactions: { good: "Ouais j'ai un peu de mal avec le silence…", neutral: "Mouais 🤔", bad: "T'aurais pas dû trouver ça normal." },
    },
    { type: 'choice', text: "T'as une soirée entre amis. Tu m'invites ou je viens pas ?", topic: 'Possessif',
      choices: [
        { label: "Je t'invite si on est assez proches oui",          icon: '🎉', value: 'green' },
        { label: "Ça dépend si c'est le bon moment dans la relation", icon: '🤔', value: 'neutral' },
        { label: "Je préférerais qu'on soit tout le temps ensemble",  icon: '🔒', value: 'red' },
      ],
      reactions: { green: "Bien. T'es correct(e) là-dessus.", neutral: "Le bon moment… ok je vois.", red: "Exactement. Comme ça pas de questions à se poser 😌" },
    },
    { type: 'flag', text: "« Mes ex disaient que j'étais trop possessif »", topic: 'Gênant en société', correct: 'red',
      reactions: { good: "T'as vu ce que mes ex ont pas su voir : c'était de l'amour pas de la possession.", neutral: "Réponse safe 🤔", bad: "T'aurais dû sonner l'alarme là." },
    },
    { type: 'choice', text: "Comment tu définirais toi-même ton charisme ?", topic: 'Peu de charisme',
      choices: [
        { label: "Je suis pas le plus charismatique mais je suis sincère", icon: '😌', value: 'green' },
        { label: "Je pense que j'ai du charme à ma façon",                icon: '😏', value: 'neutral' },
        { label: "Je suis sûr(e) de moi, je plais",                       icon: '😎', value: 'red' },
      ],
      reactions: { green: "La sincérité vaut plus que le charisme 😌", neutral: "À ta façon… j'aime cette confiance.", red: "Ok. On verra ça 😶" },
    },
    { type: 'flag', text: "« Je peux faire des scènes en public si je suis blessé »", topic: 'Gênant en société', correct: 'red',
      reactions: { good: "Ouais… j'ai du mal à retenir les émotions fortes. C'est ma façon d'être.", neutral: "T'es mitigé(e) là 🤔", bad: "Tu trouves ça normal les scènes publiques ?" },
    },
  ],
  endings: {
    smash: { emoji: '🔒', text: "T'es exactement comme ce que je cherche. Quelqu'un de stable, de présent. On peut vraiment construire quelque chose." },
    high:  { emoji: '😊', text: "C'était bien. T'es rassurant(e). J'aimerais te revoir." },
    mid:   { emoji: '🤔', text: "C'était correct mais j'ai des doutes sur notre compatibilité." },
    low:   { emoji: '😬', text: "T'es trop indépendant(e) pour moi. Ça me pèse." },
    pass:  { emoji: '🚩', text: "Non. T'es trop cool avec ton liberté perso. Ça marchera pas." },
  },
},

/* ════════════════════════════════════════
   LUCAS — Mec random sympa et posé
══════════════════════════════════════════ */
{
  id: 'lucas',
  gender: 'm',
  name: 'Lucas',
  age: 23,
  emoji: '🎸',
  avatar: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
  bio: 'Guitariste amateur, cinéma d\'auteur, bon vivant. Cherche quelqu\'un avec qui rigoler vraiment.',
  vibe: '🎸 Cool & authentique',
  flags: {
    'Musicien':           'green',
    'Cinéphile':          'green',
    'À l\'écoute':        'green',
    'Pas d\'ambition':    'red',
    'Rigolo':             'green',
    'Peu ponctuel':       'red',
    'Serein':             'green',
    'Flou sur l\'avenir': 'neutral',
  },
  warn3red:    "Ok… j'ai l'impression qu'on cherche des choses trop différentes. C'est ok.",
  smash3green: "Haha vraiment t'es quelqu'un de bien. Je m'attendais pas à autant m'amuser là 😄",
  questions: [
    { type: 'choice', text: "Je joue de la guitare depuis 6 ans, principalement pour moi. T'as un rapport avec la musique ?", topic: 'Musicien',
      choices: [
        { label: "Oui la musique c'est central dans ma vie",    icon: '🎵', value: 'green' },
        { label: "J'écoute beaucoup même si je joue pas",       icon: '🎧', value: 'neutral' },
        { label: "Pas vraiment, c'est pas mon truc",            icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Cool quelqu'un qui a ce rapport à la musique 😌", neutral: "Écouter c'est déjà beaucoup en fait.", red: "C'est ok, on peut avoir d'autres points communs." },
    },
    { type: 'flag', text: "« Je suis souvent en retard, c'est mon plus gros défaut »", topic: 'Peu ponctuel', correct: 'red',
      reactions: { good: "Ouais… je travaille là-dessus honnêtement.", neutral: "Réponse sage 🤔", bad: "T'aurais dû pointer ça." },
    },
    { type: 'choice', text: "Ciné d'auteur, films étranges, trucs qui finissent mal. T'aimes ce genre ?", topic: 'Cinéphile',
      choices: [
        { label: "Ouais j'aime les films qui me font réfléchir",  icon: '🎬', value: 'green' },
        { label: "Parfois, pas trop souvent quand même",          icon: '😌', value: 'neutral' },
        { label: "Je préfère les blockbusters honnêtement",       icon: '🍿', value: 'red' },
      ],
      reactions: { green: "On peut faire des marathons cinéma alors 😄", neutral: "Ok on mixe. C'est jouable.", red: "Blockbuster… on peut regarder ensemble quand même." },
    },
    { type: 'flag', text: "« J'ai aucun plan précis pour ma carrière »", topic: 'Flou sur l\'avenir', correct: 'neutral',
      reactions: { good: "Honnêtement… je suis serein avec ça. Ça viendra.", neutral: "Réponse équilibrée, j'apprécie.", bad: "T'as raison de pointer ça." },
    },
    { type: 'choice', text: "La qualité principale que tu cherches chez quelqu'un ?", topic: 'À l\'écoute',
      choices: [
        { label: "Qu'il·elle sache vraiment écouter",      icon: '👂', value: 'green' },
        { label: "L'humour avant tout",                    icon: '😂', value: 'neutral' },
        { label: "L'ambition et la drive",                 icon: '🎯', value: 'red' },
      ],
      reactions: { green: "Les gens qui écoutent vraiment c'est la chose la plus rare 😌", neutral: "L'humour c'est bien aussi, honnêtement.", red: "L'ambition c'est cool. Mais sans l'écoute ça tient pas." },
    },
    { type: 'flag', text: "« Je suis très à l'aise pour parler de mes émotions »", topic: 'À l\'écoute', correct: 'green',
      reactions: { good: "La maturité émotionnelle c'est le truc le plus rare chez un mec 😌", neutral: "T'es pas très convaincu(e) 🤔", bad: "Ça te semble bizarre qu'un mec parle de ses émotions ?" },
    },
    { type: 'choice', text: "Je suis pas très ambitieux dans le sens carrière. Ça te pose problème ?", topic: 'Pas d\'ambition',
      choices: [
        { label: "Non si t'es épanoui et autonome",            icon: '😌', value: 'green' },
        { label: "Un peu, j'aime les gens avec de la drive",   icon: '🤔', value: 'neutral' },
        { label: "Oui, l'ambition c'est important pour moi",   icon: '🎯', value: 'red' },
      ],
      reactions: { green: "L'épanouissement c'est mon critère à moi aussi 😌", neutral: "J'entends. J'ai de l'ambition sur ce qui compte vraiment pour moi.", red: "C'est ok. On cherche des choses différentes peut-être." },
    },
    { type: 'flag', text: "« Je fais rire les gens facilement »", topic: 'Rigolo', correct: 'green',
      reactions: { good: "C'est le plus beau compliment qu'on me fait 😄", neutral: "T'es mitigé(e) là 🤔", bad: "Tu préfères les gens sérieux à ce point ?" },
    },
  ],
  endings: {
    smash: { emoji: '😄', text: "Haha vraiment je m'attendais pas à autant kiffer ce date. T'es quelqu'un de vrai. On se revoit ?" },
    high:  { emoji: '🥰', text: "C'était vraiment sympa. T'es quelqu'un de bien, sincèrement." },
    mid:   { emoji: '🤔', text: "C'était pas mal mais j'sais pas si on est vraiment faits pour s'entendre." },
    low:   { emoji: '😬', text: "Hmm… j'ai l'impression qu'on cherche des choses trop différentes." },
    pass:  { emoji: '🚩', text: "Non, ça colle pas je pense. Bonne continuation." },
  },
},

/* ════════════════════════════════════════
   THÉO — Mec random, passionné de cuisine & voyages
══════════════════════════════════════════ */
{
  id: 'theo',
  gender: 'm',
  name: 'Théo',
  age: 25,
  emoji: '🍜',
  avatar: 'linear-gradient(135deg, #f093fb 0%, #f5a623 100%)',
  bio: 'Cuisinier passionné, globe-trotter, trop curieux. J\'ai dormi dans 11 pays différents.',
  vibe: '🍜 Curieux du monde',
  flags: {
    'Cuisine':              'green',
    'Voyages':              'green',
    'Ouverture d\'esprit':  'green',
    'Instable géographiquement': 'red',
    'Trop envahissant':     'red',
    'Généreux':             'green',
    'Passionné':            'green',
    'Peu de stabilité':     'neutral',
  },
  warn3red:    "Ok je pense qu'on vit pas du tout au même rythme. Ça risque d'être compliqué.",
  smash3green: "T'es quelqu'un qui aime vivre vraiment. C'est exactement ce que je cherche 🌍",
  questions: [
    { type: 'choice', text: "Je cuisine vraiment bien — entrée, plat, dessert, accords vins. T'aimes bien manger ?", topic: 'Cuisine',
      choices: [
        { label: "Passionnément oui, la bouffe c'est sacré",      icon: '🍽️', value: 'green' },
        { label: "J'apprécie mais je suis pas connaisseur·se",    icon: '😌', value: 'neutral' },
        { label: "Je mange pour vivre, c'est tout",               icon: '🤷', value: 'red' },
      ],
      reactions: { green: "Quelqu'un qui respecte la gastronomie. Je t'invite à dîner 😄", neutral: "Pas connaisseur·se c'est ok, je t'apprendrai.", red: "Pour vivre… t'as jamais eu un repas qui change tout ?" },
    },
    { type: 'flag', text: "« Je pars vivre 3 mois à Barcelone l'année prochaine »", topic: 'Instable géographiquement', correct: 'neutral',
      reactions: { good: "C'est un vrai choix de vie, j'assume entièrement.", neutral: "T'as bien vu la complexité de ça 😌", bad: "T'aurais dû réagir à ça." },
    },
    { type: 'choice', text: "T'as envie de voyager ou tu préfères une vie bien ancrée quelque part ?", topic: 'Voyages',
      choices: [
        { label: "Voyager c'est ce qui me fait avancer",         icon: '✈️', value: 'green' },
        { label: "Un mix : base stable et voyages réguliers",    icon: '🌍', value: 'neutral' },
        { label: "Je préfère m'enraciner, la stabilité m'importe", icon: '🏠', value: 'red' },
      ],
      reactions: { green: "On pourrait faire tellement de route ensemble 😄", neutral: "Le mix c'est ce que je cherche au fond aussi 😌", red: "La stabilité c'est beau aussi. On a juste des priorités différentes." },
    },
    { type: 'flag', text: "« Je parle trop et j'envahis l'espace parfois »", topic: 'Trop envahissant', correct: 'red',
      reactions: { good: "Ouais… je suis conscient que c'est beaucoup parfois.", neutral: "Réponse modérée 🤔", bad: "T'as pas vu de problème là ?" },
    },
    { type: 'choice', text: "Un dimanche parfait pour toi ?", topic: 'Cuisine',
      choices: [
        { label: "Marché, cuisine, repas avec des proches",    icon: '🛒', value: 'green' },
        { label: "Faire quelque chose de nouveau, découvrir",  icon: '🗺️', value: 'neutral' },
        { label: "Rester à la maison tranquille",              icon: '🛋️', value: 'red' },
      ],
      reactions: { green: "Le rituel du dimanche avec une bonne table. C'est ma définition du bonheur 😄", neutral: "Découvrir c'est aussi ça le dimanche parfait pour moi.", red: "La maison c'est bien. Mais le monde est grand 😌" },
    },
    { type: 'flag', text: "« J'ai beaucoup d'amis dans plein de pays différents »", topic: 'Ouverture d\'esprit', correct: 'green',
      reactions: { good: "Construire des liens partout c'est une richesse incroyable 😌", neutral: "T'es pas très impressionné(e) 🤔", bad: "T'as pas vu la beauté de ça ?" },
    },
    { type: 'choice', text: "Je suis généreux, parfois trop. Je donne beaucoup. T'es à l'aise pour recevoir ?", topic: 'Généreux',
      choices: [
        { label: "Oui j'aime les gens généreux et je sais recevoir",   icon: '🎁', value: 'green' },
        { label: "Ça me gêne un peu, je préfère la réciprocité",       icon: '😅', value: 'neutral' },
        { label: "Je suis très indépendant(e), j'aime pas trop recevoir", icon: '😐', value: 'red' },
      ],
      reactions: { green: "La générosité partagée c'est la base d'une belle relation 😄", neutral: "La réciprocité c'est sain, j'entends.", red: "Indépendant(e)… ok. Je ferai attention." },
    },
    { type: 'flag', text: "« J'ai des projets tous les jours et de l'énergie que je sais pas où mettre »", topic: 'Passionné', correct: 'green',
      reactions: { good: "L'énergie des passionnés c'est contagieux 🔥", neutral: "Mouais, tu sembles pas emballé(e) 🤔", bad: "C'est beaucoup pour toi ? C'est ok." },
    },
  ],
  endings: {
    smash: { emoji: '🌍', text: "T'aimes vivre et découvrir. Comme moi. Je pense qu'on pourrait faire un beau bout de chemin." },
    high:  { emoji: '🥰', text: "C'était vraiment sympa. T'as de la curiosité, ça change." },
    mid:   { emoji: '🤔', text: "T'es bien mais je me demande si mon rythme de vie c'est pour toi." },
    low:   { emoji: '😬', text: "Je pense que tu cherches quelque chose de plus stable que moi." },
    pass:  { emoji: '🚩', text: "Non. Mon mode de vie te correspond pas, c'est clair." },
  },
},

];