/* ════════════════════════════════════════
   QUESTIONS BANK
   ════════════════════════════════════════ */

const questionsF = [
  { text: "Elle vote ou soutient des partis d'extrême droite ?", label: "Extrême droite", cat: "politique" },
  { text: "Elle adhère à des idéologies nazies ou radicales ?", label: "Idéologie radicale", cat: "politique" },
  { text: "Elle est militante ultra-woke et te reprend constamment sur tes mots ?", label: "Ultra-moralisatrice", cat: "politique" },
  { text: "Elle partage des théories du complot sérieusement ?", label: "Conspirationniste", cat: "politique" },
  { text: "Elle a des valeurs familiales et voudrait des enfants ?", label: "Valeurs familiales", cat: "valeurs" },
  { text: "Elle croit que les astros déterminent la compatibilité amoureuse ?", label: "Astro-dépendante", cat: "fun" },
  { text: "Elle a des comportements ou des propos racistes ?", label: "Raciste", cat: "caractere" },
  { text: "Elle ne supporte pas la critique, même constructive ?", label: "Ego surdimensionné", cat: "caractere" },
  { text: "Elle a tendance à mentir sur de petites choses sans raison ?", label: "Tendance au mensonge", cat: "caractere" },
  { text: "Elle est végane et t'impose son régime ?", label: "Régime militant imposé", cat: "caractere" },
  { text: "Elle est sarcastique mais jamais capable de rire d'elle-même ?", label: "Humour à sens unique", cat: "caractere" },
  { text: "Elle coupe la parole systématiquement en conversation ?", label: "N'écoute pas", cat: "caractere" },
  { text: "Elle est du genre à se faire passer pour une victime dans chaque conflit ?", label: "Victim complex", cat: "drama" },
  { text: "Elle a de l'humour et te fait rire facilement ?", label: "A de l'humour", cat: "humour" },
  { text: "Elle est attentionnée et aux petits soins avec toi ?", label: "Attentionnée", cat: "relation" },
  { text: "Elle prend des décisions importantes sans jamais te consulter ?", label: "Fait cavalier seul", cat: "caractere" },
  { text: "Elle change régulièrement d'humeur de façon imprévisible ?", label: "Instabilité émotionnelle", cat: "emotion" },
  { text: "Elle fait des crises de jalousie sans raison réelle ?", label: "Jalousie excessive", cat: "emotion" },
  { text: "Elle pleure dès qu'un conflit éclate pour éviter d'en parler ?", label: "Fuite par les larmes", cat: "emotion" },
  { text: "Elle est capable de parler calmement d'un désaccord sans s'emporter ?", label: "Gestion saine des conflits", cat: "emotion" },
  { text: "Elle accumule les rancœurs sans jamais les exprimer ?", label: "Rancune silencieuse", cat: "emotion" },
  { text: "Elle exprime facilement ses émotions sans se fermer ?", label: "Ouverture émotionnelle", cat: "emotion" },
  { text: "Elle fume ?", label: "Fume", cat: "lifestyle" },
  { text: "Elle boit de l'alcool en excès ?", label: "Alcool en excès", cat: "lifestyle" },
  { text: "Elle a une forte dépendance à son téléphone et aux réseaux ?", label: "Addiction aux réseaux", cat: "lifestyle" },
  { text: "Elle fait du sport et prend soin d'elle physiquement ?", label: "Hygiène de vie saine", cat: "lifestyle" },
  { text: "Elle joue aux jeux vidéo ?", label: "Joue aux jeux vidéo", cat: "lifestyle" },
  { text: "Elle est très active sur les réseaux et follow beaucoup de mecs ?", label: "Besoin de validation online", cat: "lifestyle" },
  { text: "Elle est végane ?", label: "Végane", cat: "lifestyle" },
  { text: "Elle dort moins de 5h par nuit par choix ?", label: "Hygiène de sommeil chaotique", cat: "lifestyle" },
  { text: "Elle aime cuisiner et partager un repas fait maison ?", label: "Aime cuisiner", cat: "lifestyle" },
  { text: "Elle est accro aux dépenses impulsives sur Vinted/Shein/Amazon ?", label: "Achats compulsifs", cat: "lifestyle" },
  { text: "Son bodycount dépasse les 5 partenaires ?", label: "Bodycount élevé", cat: "passe" },
  { text: "Elle parle encore régulièrement avec un de ses exes ?", label: "Trop proche de ses exs", cat: "passe" },
  { text: "Elle voit régulièrement un de ses exes ?", label: "Voit ses exs en secret", cat: "passe" },
  { text: "Elle a eu plusieurs ruptures pour infidélité de son côté ?", label: "Antécédents d'infidélité", cat: "passe" },
  { text: "Elle parle souvent et très négativement de ses exs ?", label: "Parle mal de ses exs", cat: "passe" },
  { text: "Elle a eu des relations avec une femme ?", label: "Relations lesbiennes passées", cat: "passe" },
  { text: "Toutes ses relations se sont mal terminées pour les mêmes raisons ?", label: "Pattern négatif répété", cat: "passe" },
  { text: "Elle a une relation toxique ou distante avec ses parents ?", label: "Problèmes familiaux", cat: "social" },
  { text: "Elle a des amies proches et stables depuis longtemps ?", label: "Amitiés durables", cat: "social" },
  { text: "Elle te laisse du temps pour voir tes amis sans elle ?", label: "Respect de ton espace", cat: "social" },
  { text: "Elle parle mal de ses amies dans leur dos ?", label: "Toxique avec ses amies", cat: "social" },
  { text: "Elle est proche de sa famille et entretient de bonnes relations ?", label: "Famille soudée", cat: "social" },
  { text: "Elle est très dépensière sans s'en rendre compte ?", label: "Dépensière", cat: "pro" },
  { text: "Elle dépense plus qu'elle ne gagne et s'endette ?", label: "Mauvaise gestion financière", cat: "pro" },
  { text: "Elle est ambitieuse et investie dans ses projets ?", label: "Ambitieuse", cat: "pro" },
  { text: "Elle change de job tous les 3 mois sans raison claire ?", label: "Instabilité professionnelle", cat: "pro" },
  { text: "Elle aime créer une vraie complicité et un lien fort dans le couple ?", label: "Complicité forte", cat: "relation" },
  { text: "Elle montre facilement son affection au quotidien ?", label: "Affection exprimée", cat: "relation" },
  { text: "Elle aime les petites attentions romantiques ?", label: "Romantique", cat: "relation" },
  { text: "Elle a besoin de beaucoup de proximité émotionnelle ?", label: "Besoin de proximité", cat: "relation" },
  { text: "Elle voudrait que vous soyez ensemble 24h/24 dès le début ?", label: "Fusion excessive", cat: "drama" },
  { text: "Elle respecte tes limites quand tu en poses une ?", label: "Respecte les limites", cat: "relation" },
  { text: "Elle crée des dramas avec ses amies régulièrement ?", label: "Drama queen", cat: "drama" },
  { text: "Elle over-partage sa vie privée sur les réseaux ?", label: "Over-sharer", cat: "drama" },
  { text: "Elle a un côté compétitif qui vire à la toxicité ?", label: "Trop compétitive", cat: "drama" },
  { text: "Elle est capable de s'excuser sincèrement quand elle a tort ?", label: "Sait s'excuser", cat: "caractere" },
  { text: "Elle est d'origine latine ?", label: "Latina vibes", cat: "fun" },
  { text: "Elle est transgenre ?", label: "Transgenre", cat: "identite" },
  { text: "Elle tient la barre dans le bus / métro ?", label: "Tient la barre (respect)", cat: "fun" },
  { text: "Elle est fan d'avions / planespotting ?", label: "Fan d'avions", cat: "fun" },
  { text: "Elle écoute du true crime le soir pour s'endormir ?", label: "True crime addict", cat: "fun" },
  { text: "Elle est toujours en retard, même pour des trucs importants ?", label: "Retard chronique", cat: "energie" },
  { text: "Elle t'envoie des mèmes à 3h du mat ?", label: "Mème à 3h du mat", cat: "fun" },
  { text: "Elle passe plus de 2h par jour sur TikTok ?", label: "TikTok addict", cat: "lifestyle" },
  { text: "Elle est fan de football et regarde les matchs ?", label: "Fan de foot", cat: "fun" },
  { text: "Elle a un side project créatif (art, musique, écriture…) ?", label: "Créative", cat: "energie" },
  { text: "Elle sort tous les soires en boite ?", label: "Sort", cat: "lifestyle" },
  { text: "Elle te prévient a chque fois quelle sort ?", label: "Sort", cat: "lifestyle" },
  { text: "C'est une modo discord ?", label: "Modératrice", cat: "lifestyle" },
  { text: "Elle aime pas la musique ?", label: "Musique", cat: "lifestyle" },
];

const questionsM = [
  { text: "Il vote ou soutient des partis d'extrême droite ?", label: "Extrême droite", cat: "politique" },
  { text: "Il adhère à des idéologies nazies ou radicales ?", label: "Idéologie radicale", cat: "politique" },
  { text: "Il est misogyne ou tient des propos sexistes régulièrement ?", label: "Misogyne / sexiste", cat: "politique" },
  { text: "Il partage des théories du complot sérieusement ?", label: "Conspirationniste", cat: "politique" },
  { text: "Il a des valeurs familiales et voudrait des enfants ?", label: "Valeurs familiales", cat: "valeurs" },
  { text: "Il croit que les astros déterminent la compatibilité amoureuse ?", label: "Astro-dépendant", cat: "fun" },
  { text: "Il a des comportements ou des propos racistes ?", label: "Raciste", cat: "caractere" },
  { text: "Il ne supporte pas la critique, même constructive ?", label: "Ego surdimensionné", cat: "caractere" },
  { text: "Il a tendance à mentir sur de petites choses sans raison ?", label: "Tendance au mensonge", cat: "caractere" },
  { text: "Il est végane et t'impose son régime ?", label: "Régime militant imposé", cat: "caractere" },
  { text: "Il est sarcastique mais jamais capable de rire de lui-même ?", label: "Humour à sens unique", cat: "caractere" },
  { text: "Il coupe la parole systématiquement en conversation ?", label: "N'écoute pas", cat: "caractere" },
  { text: "Il se fait passer pour une victime dans chaque conflit ?", label: "Victim complex", cat: "drama" },
  { text: "Il a de l'humour et te fait rire facilement ?", label: "A de l'humour", cat: "humour" },
  { text: "Il est attentionné et aux petits soins avec toi ?", label: "Attentionné", cat: "relation" },
  { text: "Il prend des décisions importantes sans jamais te consulter ?", label: "Fait cavalier seul", cat: "caractere" },
  { text: "Il change régulièrement d'humeur de façon imprévisible ?", label: "Instabilité émotionnelle", cat: "emotion" },
  { text: "Il fait des crises de jalousie sans raison réelle ?", label: "Jalousie excessive", cat: "emotion" },
  { text: "Il s'énerve dès qu'un conflit éclate au lieu d'en parler ?", label: "Fuite par la colère", cat: "emotion" },
  { text: "Il est capable de parler calmement d'un désaccord sans s'emporter ?", label: "Gestion saine des conflits", cat: "emotion" },
  { text: "Il accumule les rancœurs sans jamais les exprimer ?", label: "Rancune silencieuse", cat: "emotion" },
  { text: "Il exprime facilement ses émotions sans se fermer ?", label: "Ouverture émotionnelle", cat: "emotion" },
  { text: "Il fume ?", label: "Fume", cat: "lifestyle" },
  { text: "Il boit de l'alcool en excès ?", label: "Alcool en excès", cat: "lifestyle" },
  { text: "Il a une forte dépendance à son téléphone et aux réseaux ?", label: "Addiction aux réseaux", cat: "lifestyle" },
  { text: "Il fait du sport et prend soin de lui physiquement ?", label: "Hygiène de vie saine", cat: "lifestyle" },
  { text: "Il joue aux jeux vidéo ?", label: "Joue aux jeux vidéo", cat: "lifestyle" },
  { text: "Il est très actif sur les réseaux et follow beaucoup de filles ?", label: "Besoin de validation online", cat: "lifestyle" },
  { text: "Il est végane ?", label: "Végane", cat: "lifestyle" },
  { text: "Il dort moins de 5h par nuit par choix ?", label: "Hygiène de sommeil chaotique", cat: "lifestyle" },
  { text: "Il aime cuisiner et partager un repas fait maison ?", label: "Aime cuisiner", cat: "lifestyle" },
  { text: "Il dépense tout son salaire en sneakers / hype culture ?", label: "Achats compulsifs", cat: "lifestyle" },
  { text: "Son bodycount dépasse les 5 partenaires ?", label: "Bodycount élevé", cat: "passe" },
  { text: "Il parle encore régulièrement avec une de ses exes ?", label: "Trop proche de ses exs", cat: "passe" },
  { text: "Il voit régulièrement une de ses exes ?", label: "Voit ses exs en secret", cat: "passe" },
  { text: "Il a eu plusieurs ruptures pour infidélité de son côté ?", label: "Antécédents d'infidélité", cat: "passe" },
  { text: "Il parle souvent et très négativement de ses exes ?", label: "Parle mal de ses exs", cat: "passe" },
  { text: "Il a eu des relations avec un homme ?", label: "Relations homo passées", cat: "passe" },
  { text: "Toutes ses relations se sont mal terminées pour les mêmes raisons ?", label: "Pattern négatif répété", cat: "passe" },
  { text: "Il a une relation toxique ou distante avec sa mère ?", label: "Problèmes familiaux", cat: "social" },
  { text: "Il a des amis proches et stables depuis longtemps ?", label: "Amitiés durables", cat: "social" },
  { text: "Il te laisse du temps pour voir tes amis sans lui ?", label: "Respect de ton espace", cat: "social" },
  { text: "Il parle mal de ses amis dans leur dos ?", label: "Toxique avec ses amis", cat: "social" },
  { text: "Il est proche de sa famille et entretient de bonnes relations ?", label: "Famille soudée", cat: "social" },
  { text: "Il est très dépensier sans s'en rendre compte ?", label: "Dépensier", cat: "pro" },
  { text: "Il dépense plus qu'il ne gagne et s'endette ?", label: "Mauvaise gestion financière", cat: "pro" },
  { text: "Il est ambitieux et investi dans ses projets ?", label: "Ambitieux", cat: "pro" },
  { text: "Il change de job tous les 3 mois sans raison claire ?", label: "Instabilité professionnelle", cat: "pro" },
  { text: "Il aime créer une vraie complicité et un lien fort dans le couple ?", label: "Complicité forte", cat: "relation" },
  { text: "Il montre facilement son affection au quotidien ?", label: "Affection exprimée", cat: "relation" },
  { text: "Il aime les petites attentions romantiques ?", label: "Romantique", cat: "relation" },
  { text: "Il a besoin de beaucoup de proximité émotionnelle ?", label: "Besoin de proximité", cat: "relation" },
  { text: "Il voudrait que vous soyez ensemble 24h/24 dès le début ?", label: "Fusion excessive", cat: "drama" },
  { text: "Il respecte tes limites quand tu en poses une ?", label: "Respecte les limites", cat: "relation" },
  { text: "Il crée des dramas avec ses amis régulièrement ?", label: "Drama king", cat: "drama" },
  { text: "Il over-partage sa vie privée sur les réseaux ?", label: "Over-sharer", cat: "drama" },
  { text: "Il a un côté compétitif qui vire à la toxicité ?", label: "Trop compétitif", cat: "drama" },
  { text: "Il est capable de s'excuser sincèrement quand il a tort ?", label: "Sait s'excuser", cat: "caractere" },
  { text: "Il est d'origine latine ?", label: "Latino vibes", cat: "fun" },
  { text: "Il est transgenre ?", label: "Transgenre", cat: "identite" },
  { text: "Il tient la barre dans le bus / métro ?", label: "Tient la barre (respect)", cat: "fun" },
  { text: "Il est fan d'avions / planespotting ?", label: "Fan d'avions", cat: "fun" },
  { text: "Il écoute du true crime le soir pour s'endormir ?", label: "True crime addict", cat: "fun" },
  { text: "Il est toujours en retard, même pour des trucs importants ?", label: "Retard chronique", cat: "energie" },
  { text: "Il t'envoie des mèmes à 3h du mat ?", label: "Mème à 3h du mat", cat: "fun" },
  { text: "Il passe plus de 2h par jour sur TikTok ?", label: "TikTok addict", cat: "lifestyle" },
  { text: "Il est fan de football et regarde tous les matchs ?", label: "Fan de foot", cat: "fun" },
  { text: "Il a un side project créatif (art, musique, écriture…) ?", label: "Créatif", cat: "energie" },
];